### ISSUE TITLE
sdk里FriendAdmin.java里的getFriendStatusList方法有bug

### ISSUE THREAD

**Issue by hmilvu** [wildfirechat/im-app_server#1]
在FriendAdmin类里getFriendStatusList是根据状态去获取好友，方法的参数里传了status，但是获取的永远都是status=0的好友，应该是input.setStatus(0)改成input.setStatus(status)

    public static IMResult<Void> getFriendStatusList(String userId, int status) throws Exception {
        String path = "/admin/friend/list";
        InputGetFriendList input = new InputGetFriendList();
        input.setUserId(userId);
        **input.setStatus(0);**
        return AdminHttpUtils.httpJsonPost(path, input, Void.class);
    }

**Comment by heavyrain2012** [comment]
已经解决，多谢提醒
