### ISSUE TITLE
新库有问题

### ISSUE THREAD

**Issue by woyaozuoai** [wildfirechat/im-app_server#12]
服务端布置成功,手机app列表不加载好友对话，对话内容不能收到但是数据库里面有内容了,需要删除对话从新拉取才能获取内容(新内容重复此操作)。

**Comment by heavyrain2012** [comment]
IM服务配置文件中有个配置参数message.roaming 打开就能收到历史消息了

**Comment by woyaozuoai** [comment]
> IM服务配置文件中有个配置参数message.roaming 打开就能收到历史消息了

不是这个问题啊！！ 是发送内容给好友,好友不能收到内容但是数据库有内容需要删除会话后才能获取新内容

**Comment by heavyrain2012** [comment]
你说的新库是什么库，换回原来的就没有问题是吗？还有用demo对比过吗
