### ISSUE TITLE
Error parsing HTTP request header

### ISSUE THREAD

**Issue by ZYuanCheng** [wildfirechat/im-app_server#24]
o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
<img width="897" alt="1641266914(1)" src="https://user-images.githubusercontent.com/30103415/148005796-6bd6c1bc-2787-4719-bcc5-08af5632c931.png">

**Comment by heavyrain2012** [comment]
这个是怎么发生的？这个项目都是开源的，你们可以查一下看看原因

**Comment by ZYuanCheng** [comment]
在阿里云服务器windows server 2019 Datacenter服务启动后没有过了一天发现请求不了，控制台打印这个错误，只能重启服务。

**Comment by heavyrain2012** [comment]
这个错误应该不是导致请求不了的原因，还有没有更多的日志，这个应用服务是全部开源的，你们可以多加点儿日志看看

**Comment by heavyrain2012** [comment]
no response
