### ISSUE TITLE
 Error executing DDL

### ISSUE THREAD

**Issue by strin-sr** [wildfirechat/im-app_server#28]
GenerationTarget encountered exception accepting command : Error executing DDL "create index IDXqfhd900v364vou
p4hhkn811w4 on t_favorites (user_id, type)" via JDBC Statement

**Comment by heavyrain2012** [comment]
这个服务所有的代码都是开源的，你们可以自己来查一下是什么问题，猜测可能跟数据库的版本有关，如果查到原因了请告诉我们，谢谢
