### ISSUE TITLE
Group type is getting changed as restricted

### ISSUE THREAD

**Issue by Sadakhatali** [wildfirechat/im-app_server#29]
Dear Team,
    As part of our project requirement we wanted to understand below points, related to group creation.
    
    1. What are the possible ways to changing the group type.
    2. Where do we have a logic to change the group type I mean group type logic has been implemented at front end or backed.

**P.S:** While group creation from front end always we are passing the group type as 0 (GroupType_Normal) but some times group is getting created as type 2 (GroupType_Restricted), we required your help to understand from where the type is getting changed, we are unable to trace in the code.

**Comment by heavyrain2012** [comment]
重复 https://github.com/wildfirechat/im-server/issues/469
