### ISSUE TITLE
你好，关于服务端主动发送给Android端消息

### ISSUE THREAD

**Issue by heli-boop** [wildfirechat/im-app_server#33]
你好 打扰了 我想发送消息的时候，能判断用户的在线状态；比如用户在线了我才发送消息。现在我在客户端自定了消息类型，同时调用SDK中的message/send去发送消息，其中消息的payload设置为payload.setPersistFlag(4);如此客户端只会在线的时候收到消息；但是我服务端无法感知到，就是调用此方法给一个不在线的用户发送，依然返回给我成功的状态；
1、我想要的是如果用户不在线或者用户断网了，发送的结果告诉我发送失败（因为我的应用特殊需要在发送失败的时候走短信通道）。
2、我后来在API中 找到/admin/user/onlinestatus这个方法，发送之前提前判断用户在线状态。但是此方法的返回的session中的状态感觉不是那么精准，是跟IM的心跳有关系吗。客户端已经推出去很久了，依然返回在线状态，不知道是什么机制，能说明下吗

感谢解答

**Comment by imndx** [comment]
是的，和心跳有有关。

是不是这样做更合适：

1. 业务服务调用```server api```发送自定义消息之后，记录一下给谁发送了自定义消息
2. 客户端收到自定义消息之后，主动向业务服务上报已收到，
3. 业务服务采用定时任务去查询自定义消息的送达情况，如果多长时间客户端没有主动上报已收到，则表示未送达，那么走短信逻辑。

**Comment by imndx** [comment]
补充一下：

专业版 IM-Server 支持查询消息的送达、阅读状态，基于这个也能实现

**Comment by heli-boop** [comment]
要查询 还是不行；我们带宽也很低，大概相当于GSM网络。我看到那个查询用户在线状态的session里面有个上次的时间，是代表最后一次心跳的时间？拿这个时间和心跳间隔来判断 是不是可以得到一个稍微精确的用户在线状态？请问这个心跳时间在客户端里面设置吗？

**Comment by imndx** [comment]
查询是服务端对服务操作，甚至业务服务可以直接和 IM-Server 部署在同一个内网

```session```里面的```lastActivieTime```表示的不是心跳时间，而是类似最后一次收发消息等 IM 操作的时间，并且心跳不是固定的，而是动态的
