### ISSUE TITLE
0.62的deb包无法使用

### ISSUE THREAD

**Issue by YiuTerran** [wildfirechat/im-app_server#35]
dpkg -i app-server-0.62.deb

Preparing to unpack app-server-0.62.deb ...
Unpacking app-server (0.62) over (0.62) ...
Setting up app-server (0.62) ...
mv: cannot stat '/opt/app-server/app-*.jar': No such file or directory

**Comment by heavyrain2012** [comment]
请使用下面这个命令安装:
```
sudo apt install ./app-server-0.62.deb
```

 另外换到最新的版本试试
