### ISSUE TITLE
获取用户状态

### ISSUE THREAD

**Issue by awei12121** [wildfirechat/im-app_server#36]
IMResult<OutputCheckUserOnline> outputCheckUserOnline = UserAdmin.checkUserOnlineStatus(userInfo.getUserId());
        if (outputCheckUserOnline != null && outputCheckUserOnline.getErrorCode() == ErrorCode.ERROR_CODE_SUCCESS) {
            System.out.println("check user online status success:" + outputCheckUserOnline.getResult().getSessions().size());
         // outputCheckUserOnline.getResult().getSessions().size()  用户状态是这个size()??????

        } else {
            System.out.println("block user online failure");
            System.exit(-1);
        }

**Comment by heavyrain2012** [comment]
getSessions是在线的客户端的信息
