### ISSUE TITLE
短信服务

### ISSUE THREAD

**Issue by wondenful** [wildfirechat/im-app_server#39]
为什么在 android-chat 项目里面没有配置 tencent_sms.properties ，不就没有办法更换信息服务功能吗？

**Comment by imndx** [comment]
因为短信验证码相关功能是在这个项目处理的，`android-chat`只会调用这个服务的接口，然后由`app-server`来实际调用服务商的短信接口，进行发送验证码短信。

**Comment by wondenful** [comment]
是需要把 app-server 下载，放到项目 android-chat 里面进行修改吗？还是新建一个项目配置 app-serve ？

**Comment by wondenful** [comment]
可以详细教我吗？求求了

**Comment by wondenful** [comment]
可以详细教我吗

**Comment by imndx** [comment]
`app-server`是单独的一个服务，需要单独部署。

可以参考[快速开始](https://docs.wildfirechat.cn/quick_start/)
