### ISSUE TITLE
im server专业版的 Dockerfile JVM内存参数设置问题

### ISSUE THREAD

**Issue by neversuspend** [wildfirechat/im-app_server#43]
RUN sed -i 's/#JAVA_OPTS="$JAVA_OPTS -Xmx128M"/JAVA_OPTS="$JAVA_OPTS -Xmx$JVM_XMX"/g' /opt/im-server/bin/wildfirechat.sh
RUN sed -i 's/#JAVA_OPTS="$JAVA_OPTS -Xms128M"/JAVA_OPTS="$JAVA_OPTS -Xms$JVM_XMS"/g' /opt/im-server/bin/wildfirechat.sh

Dockerfile 的这段话是不是需要修改

wildfirechat.sh 里面只有

echo "警告：没有设置JVM内存参数！"
echo "请设置JVM参数Xmx和Xms，设置为您为IM服务预留的内存大小，注意需要刨除操作系统占用，如果有其它系统也需要相应去除占用。"
echo ""
#JAVA_OPTS="$JAVA_OPTS -Xmx2G"
#JAVA_OPTS="$JAVA_OPTS -Xms2G"

谢谢。

**Comment by heavyrain2012** [comment]
使用docker启动，不需要关注这段话，因为docker启动命令中带有jvm的参数，可以忽略这个提示
