### ISSUE TITLE
im sever专业版启动时候 报 Name of the hazelcast schema location is incorrect

### ISSUE THREAD

**Issue by neversuspend** [wildfirechat/im-app_server#44]
im-server   | Sep 09, 2024 4:25:47 AM com.hazelcast.config.FileSystemXmlConfig
im-server   | INFO: Configuring Hazelcast from '/opt/im-server/config/hazelcast.xml'.
im-server   | Sep 09, 2024 4:25:47 AM com.hazelcast.config.AbstractXmlConfigHelper
im-server   | WARNING: Name of the hazelcast schema location is incorrect, using default

**Comment by heavyrain2012** [comment]
这个是warning，不影响正常使用的。你们测试看看有没有别的问题
