### ISSUE TITLE
application.properties文件里面设置了sms.super_code=66666不起作用啊，登录测试填写6666仍然失败

### ISSUE THREAD

**Issue by allenlei2010** [wildfirechat/im-app_server#5]
application.properties文件里面设置了sms.super_code=66666不起作用啊，登录测试填写6666仍然失败，获取验证码的话就真的发短信了收到短信验证是通过的。
以下是 application.properties文件 内容： spring.message.encoding=UTF-8 server.port=8888

sms.verdor=1

sms.super_code=66666

**Comment by imndx** [comment]
你好，请确认下配置的```super_code```和你登录时填写的是否一致。

上面你的描述，你配置的5个6，填写的是4个6

**Comment by allenlei2010** [comment]
确认了，sms.super_code=66666，登录时填写的也是66666，仍然是失败。

**Comment by heavyrain2012** [comment]
是不是在windows上编辑导致文件格式有变化，请试试在linux服务器上直接修改试试

**Comment by allenlei2010** [comment]
windows和linux上都试过了，还是一样的存在问题

**Comment by allenlei2010** [comment]
咱们有qq群或者微信群嘛？我可以把我这的配置发过去

**Comment by heavyrain2012** [comment]
你试试什么都不改的情况下，传到linux服务器，然后在服务器上修改看看
