### ISSUE TITLE
org.apache.shiro.authc.AuthenticationException: 会话不存在

### ISSUE THREAD

**Issue by ladixiu** [wildfirechat/im-app_server#9]
![image](https://user-images.githubusercontent.com/43605070/79968686-0d9b6b80-84c3-11ea-816f-127754c538eb.png)
![image](https://user-images.githubusercontent.com/43605070/79968727-1db34b00-84c3-11ea-80bd-c0aaa5ef94f5.png)

![image](https://user-images.githubusercontent.com/43605070/79968852-463b4500-84c3-11ea-86c5-e58131b67883.png)

这个是啥问题，

**Comment by xuecanlong** [comment]
我是登录的时候遇到这个问题 验证码收到了 但是登录不进去

**Comment by xuecanlong** [comment]
我更新到0.42就解决了
